config/routes.rb
MainRailsServer::Application.routes.draw do

  resources :feedback, :only => [:new, :create]

  match "close_fancybox" =>  "home#close_fancybox"
  match "about_us" =>  "home#about_us"
  match "csp_report" =>  "home#csp_report"

  scope "events" do
    match "upload_bulk"  =>  "events#upload_bulk"
    match "delete"  =>  "events#delete"
    match "poll"    =>  "events#poll"
  end
  resources :events

  scope "users" do
    match "init"    =>  "users#init"
    match "check_phone_number"    =>  "users#check_phone_number"
    match "verify_password"    =>  "users#verify_password"
    match "phone/:phone_number" =>  "users#show"
  end

  resources :user_sessions
  match 'login/:width/:height' => 'user_sessions#new', :as => :login
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  constraints :phone_number => /\d+/ do
    match ":phone_number"  => "events#calendar"
    match ":phone_number/map/:id"     => "events#map"
    match ":phone_number/new"     => "events#new"
    match ":phone_number/charts"     => "events#charts"
	match ":phone_number/timeline"     => "events#timeline"
	match ":phone_number/table"     => "events#table"
  end

  root :to => "events#calendar"

end

app/models/event.rb
require 'uuidtools'

class Event < ActiveRecord::Base
  belongs_to :user
  before_create :init_defaults
  DATE_TIME_FORMAT = '%I:%M%p %b %d, %Y'

  validates :user_id, :presence => true

  def Event.time_long_to_s(long_time)
    epoch_time = Time.at(long_time / 1000)
    epoch_time.strftime(DATE_TIME_FORMAT)
  end

  def Event.time_s_to_long(string_time)
    dt = DateTime.strptime(string_time, DATE_TIME_FORMAT)
    dt.advance(:hours => 8).to_time.to_i * 1000
  end

  def check_start_time_before_end(start_time, end_time)
    errors.add_to_base('Start time must be before end time.') if start_time > end_time
  end

  def init_defaults
    self.uuid = UUIDTools::UUID.timestamp_create().to_s unless !self.uuid.nil?
    self.content = '{}' unless !self.content.nil?
    self.deleted = false unless !self.deleted.nil?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:poll,:upload_bulk, :delete]
  skip_before_filter :set_csp, :only => :charts
  before_filter :set_local_csp, :only => :charts

  # Sets the content security policy by modifying the http headers
  def set_local_csp
    response.headers['X-Content-Security-Policy'] = "default-src 'self'; script-src 'self' https://www.google.com; options inline-script eval-script; report-uri http://127.0.0.1:3000/csp_report"
  end
  # GET /:phone_number/table
  def table
    phone_number = params[:phone_number]
    @user = User.find_by_phone_number(phone_number)
    @user = User.find_by_phone_number(get_modified_phone_number(phone_number)) unless @user
    if !@user
      redirect_to '/', :notice => "Please log in with your phone number."
      return
    elsif !verify_user(@user)
      return
    end
    @events = Event.find(:all, :conditions => {:user_id => @user.id, :deleted => false}) unless @user.nil?

    @contents = @events.collect {|event|
	event.content
    }
    @contents = @contents.to_json

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {:contents => @events.as_json}}
      format.xml  { render :xml => @events }
    end
  end

  # GET /:phone_number/charts
  def charts
    @user = User.find_by_phone_number(params[:phone_number])
    if !verify_user(@user)
      return
    end
    @events = Event.find(:all, :conditions => {:user_id => @user.id, :deleted => false}) unless @user.nil?
    @contents = @events.collect {|event|
     # ActiveSupport::JSON.decode(event.content)
	event.content
    }
    @contents = @contents.to_json
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # The root of the site is routed to this action
  def calendar
    if current_user
	  current_phone_number = current_user.phone_number
	end
    @user = User.find_by_phone_number(params[:phone_number]) || User.find_by_phone_number(current_phone_number)
    if !verify_user_calendar(@user)
      @user = User.new
	  @user.phone_number = "123456" #dummy phone number
	  @events=[]
	  @contents=[]
	  #used for displaying the login box in the calendar view
	  @need_to_login = true
	else
	  @need_to_login = false
      @events = Event.find(:all, :conditions => {:user_id => @user.id, :deleted => false}) unless @user.nil?
      @contents = @events.collect {|event|
       # ActiveSupport::JSON.decode(event.content)
	    event
      }
      @contents = @contents.to_json
	end


    respond_to do |format|
      format.json { render :json => {:phone_number => @user.phone_number, :contents => @events.as_json, :need_to_login => @need_to_login }}
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end



# GET /:phone_number/timeline
  def timeline
    @user = User.find_by_phone_number(params[:phone_number])
    if !verify_user(@user)
      return
    end
    @events = Event.find(:all, :conditions => {:user_id => @user.id, :deleted => false}) unless @user.nil?
    @contents = @events.collect {|event|
     # ActiveSupport::JSON.decode(event.content)
	event
    }
    @contents = @contents.to_json


    respond_to do |format|
      format.json { render :json => {:phone_number => @user.phone_number, :contents => @events.as_json}}
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  def poll
    if params['PollTime']
      previous_poll_time = DateTime.parse(params['PollTime'])
      puts previous_poll_time
      # TODO fix this bad code/ordering
    end
    user = User.find_by_uuid(params['uuid'])
    if previous_poll_time then
      events = Event.find( :all, :conditions => ["updated_at > ? AND user_id = ?", previous_poll_time, user.id] )
    else
      events = Event.find(:all, :conditions => {:user_id => user.id, :deleted => false})
    end
    events_to_send = events.collect do |event|
	   event_data = {}
       event_data['content'] = event.content
       event_data['uuid'] = event.uuid
       event_data['updated_at'] = event.updated_at.to_s
       event_data['deleted'] = event.deleted
       event_data
    end

    response = {'pollTime' => DateTime.now, 'events' => events_to_send }

    render :json => response, :status => 200
  end

  # GET /events/map/:phone_number
  def map
    @event = Event.find(params[:id])
    @contents = @event.content.to_json
    @user = User.find(@event.user_id)
    if !verify_user(@user)
      return
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])
    @user = User.find(@event.user_id)
    if !verify_user(@user)
      return
    end
    @contents = @event.content.to_json
    @edit_fields = {'name' => 'Name', 'tag' => 'Category', 'notes' => 'Notes', 'startTime' => 'Start Time'}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => {:contents => @event.as_json}}
      format.xml  { render :xml => @event }
    end
  end

  # GET /:phone_number/new
  # This is called when a new event is being created
  def new
    @event = Event.new
    @user = User.find_by_phone_number(params[:phone_number])
    if !verify_user(@user)
      return
    end
    @event.user_id = @user.id
    @edit_fields = {'name' => 'Name', 'tag' => 'Category', 'notes' => 'Notes', 'startTime' => 'Start Time'}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => {:contents => nil}}
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  # Called when an event is being edited
  def edit
    logger.debug "edit"
    @event = Event.find(params[:id])
    @user = User.find(@event.user_id)
    if !verify_user(@user)
      return
    end
    @contents = @event.content.to_json
    @edit_fields = {'name' => 'Name', 'tag' => 'Category', 'notes' => 'Notes', 'startTime' => 'Start Time'}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => {:contents => @event.as_json}}
      format.xml  { render :xml => @event }
    end
  end

  # POST /events
  # POST /events.xml
  # This method is called when the form for creating an event is submitted
  def create
    if params[:event]
      raise Exception
      #@event = Event.find(params[:event])
    else
      @event = Event.new
      @event.user_id = params[:user][:id]
    end
    if params[:content][:b]
      @event.content = params[:content][:b]
    end

    user = User.find(@event.user_id)
    if !verify_user(user)
      return
    end
    respond_to do |format|
      if @event.save
#        format.html { redirect_to("/#{user.phone_number}", :notice => 'Event was successfully created.') }
        format.html { redirect_to "/close_fancybox" }
        format.xml  { head :ok }
      else
        @contents = contents.to_json
        format.html { render :action => "edit" }
        format.xml  { render :xml => event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # POST /events/1
  # This method is called when the form for creating an event is submitted
  def update
    event = Event.find(params[:id])
    event.content = params['content']['b']

    user = User.find_by_id(params['user']['id'])
    if !verify_user(user)
      return
    end

    respond_to do |format|
      if event.save
        #format.html { redirect_to("/#{user.phone_number}", :notice => 'Event was successfully updated.') }
        format.html { redirect_to '/close_fancybox' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    event = Event.find(params[:id])
    user = User.find(event.user_id)

    if !verify_user(user)
      return
    end
    event.deleted = true
    event.save

    respond_to do |format|
      format.html { redirect_to(:back) }
      format.xml  { head :ok }
    end
  end

  # DELETE /events/delete
  # Called from the phone when the user has deleted an event
  def delete
    uuid = params[:UUIDOfEvent]
    user_uuid = params[:uuid]
    errors = false
    if uuid and user_uuid then
      @event = Event.find_by_uuid(uuid)
      # user_uuid must match
      if @event
        errors = @event.user_id == User.find_by_uuid(user_uuid)
      else
        errors = true
      end
    else
      # must pass uuid and device uuid
      errors = true
    end
    @event.deleted = true

    if errors or !@event.save
      render :text => 'Could not delete', :status => 400
    else
      render :text => 'OK', :status => 200
    end
  end

  # POST /events/upload_bulk
  def upload_bulk
    event_data = ActiveSupport::JSON.decode(params[:EventData])

    user = User.find_by_uuid(params[:uuid])

    event_data.each do |event_datum|
      event = Event.find_or_create_by_uuid(event_datum["UUIDOfEvent"])
      if received_event_outdated?(event_datum, event)
        success = true
      else
        event.user_id = user.id unless user.nil?
        event.content = event_datum["EventData"]
        event.deleted = event_datum["Deleted"]
        event.updated_at = DateTime.parse(event_datum["UpdatedAt"])
        success = event.save
      end

      if !success
        render :text => event.errors.to_s, :status => 400
        return
      end
    end

    render :text => 'OK', :status => 200
  end

  private

  def verify_user_calendar(user)
    if !current_user || current_user.phone_number != user.phone_number
      return false
    end
    return true
  end

  # Returns true if the received event data is outdated, otherwise false.
  def received_event_outdated?(received_datum, existing_event)
    if !existing_event.persisted?
      return false # if there was no previous event, this is new data
    else

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<!--
This partial view is used to both show events and create events
-->
<STYLE TYPE="text/css">
  .inputfield  {
    width: 350px;
    font-size:100%}
  }
</STYLE>
<table>
<% @edit_fields.each do |field, name| %>
  <% if name == 'Notes'%>
      <td><%= label :content, name %> </td>
      <td><%= text_area :content, field, :id => field, :rows => "2",
        :class => 'inputfield'%> </td>
  <% else %>
    <tr>
      <td><%= label :content, name %> </td>
      <td><%= text_field :content, field, :id => field, :value => "",
          :class => 'inputfield' %></td>
    </tr>
  <% end %>
<% end %>
  <tr>
    <td><%= label :content, 'End time' %> </td>
    <td><%= text_field :content, 'endTime', :id => 'endTime', :value => "",
            :class => 'inputfield'%></td>
  </tr>
</table>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= hidden_field :content, 'b', :id => 'encrypted_content', :value => "" %>
  </div>
  <%= hidden_field(:user, :id, :value => @event.user_id) %>
  <div class="actions" style='display:none;'>
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript" src="/csp_scripts/show_event.js"></script>

app/views/events/calendar.html.erb
<!-- This hidden link is used by fancybox in order to display a login box if
     the user needs to login -->
<%= feedback_includes %>
<a class="iframe" style="display:none;" id="hidden_link" href="/login"></a>
<link rel='stylesheet' type='text/css' href='/fullcalendar/fullcalendar.css' />
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8"> </script>
<script type='text/javascript' src='/fullcalendar/fullcalendar.js'></script>
<link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen, projection" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="/csp_scripts/calendar.js"></script>
<ul id="toolbar" class="ui-helper-reset ui-helper-clearfix ui-widget-header
                        ui-corner-all">
  <%= link_to 'Create a new Event', "/#{@user.phone_number}/new",:class => 'create_event' %>
  <%= link_to 'View Pie Chart', "/#{@user.phone_number}/charts", :class => 'pi_chart' %>
  <%= link_to 'View Timeline', "/#{@user.phone_number}/timeline", :class => 'timeline' %>
  <%= link_to 'View Table', "/#{@user.phone_number}/table", :class => 'table' %>
  <button id="logout" type="button" style = "float:right;"> Logout </button>
</ul>
<br /> <br />
<div id='calendar'></div>
<div id="dialog" title="Dialog Title"></div>

app/views/events/charts.html.erb
<script type='text/javascript' src='/fullcalendar/fullcalendar.js'></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type='text/javascript' src='/datejs/date.js'></script>
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8"> </script>
<link href="/stylesheets/protovis.tipsy.css" type="text/css" rel="stylesheet"/>
<style type="text/css">
  [type="button"] {
    font-size: 1em;
  }

  #pickerContainer {
    margin-top:.9em;
  }
</style>

<div id="chart_div"></div>
<div class="buttonContainer">
  <button id="prevBtn" type="button"></button>
  <button id="nextBtn" type="button"></button>
</div>
<div id="pickerContainer" class="buttonContainer">
  Start Date: <input type="text" id="startPicker" class="datepicker" size="7">
  End Date: <input type="text" id="endPicker" class="datepicker" size="7">
</div>

<script type="text/javascript">
  unencryptedEvents = encryptionHelpers.unpackEncryptedEvents(<%= raw @contents %>)
</script>	
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(updatePieChart);

  var tagTimes=new Array();	
  // Data structure used to easily convert between the view used by the calendar
  //   and the labels used by the next/prev buttons
  var convertViewToDate = {'agendaDay': 'day', 'agendaWeek': 'week', 'month': 'month'}

  // invariant: User visited calendar before visiting pie chart. Make sure this is always true

  var startDate = new Date(sessionStorage.getItem('startDate'));
  //The end Date is exclusive. 
  var endDate = new Date(sessionStorage.getItem('endDate')).add(-1).days().set({hour: 23, minute: 59, second:59 })
  var pieChartTitle = sessionStorage.getItem('pieChartName');
  var calendarView = sessionStorage.getItem('view');

  //For the events given, groups the events by tags and computes the time that each group of events took.
  function computeTagTimes(filteredEvents) {
    for(var i=0; i< filteredEvents.length; i++){
      var event = filteredEvents[i];
      var startTime = event['startTime'];
      var endTime = event['endTime'];
      var totalTime = (endTime - startTime) * 1.0 / (1000 * 60 * 60);
      var tag = event['tag'];
      if (tag==null || tag=='Select a tag') {
        tag='Other';	
      }
      var prevValue=tagTimes['tag'];
      if (prevValue==null) {
        prevValue=0;
      }
		  tagTimes[tag]=prevValue+totalTime;	
    }
  }

  // Returns the title of the pie chart that reflects what range of dates the pie chart is covering.
  // The parameter selectDates is true if the range of dates was user selected.
  function computeTitle(selectDates) {
    if (selectDates == true) {
      return $.fullCalendar.formatDate(startDate, "MMM dd, yyyy") + " to " +
          $.fullCalendar.formatDate(endDate, "MMM dd, yyyy");
    } 
    else if (calendarView == 'month') {
      return $.fullCalendar.formatDate(startDate, "MMM yyyy");
    }
    else if (calendarView == 'agendaWeek') {
      // The end date is exclusive. Therefore we must subtract one day.
      return $.fullCalendar.formatDate(startDate, "MMM dd, yyyy") + " to " +
          $.fullCalendar.formatDate(endDate, "MMM dd, yyyy");
    }   
    else if (calendarView == 'agendaDay'){
      return $.fullCalendar.formatDate(startDate, "MMM dd, yyyy");
    }
  }


  // Function that we use to filter with
  function filterDateFunction(activity, index) {
    var startTime = activity['startTime'];
    return startTime > startDate && startTime < endDate;
  }

  // Grep is the Jquery equivalent of the higher order function filter.
  // Returns a new array of events consisting of all elements that the filter
  //  function filterDateFunction returned true for
  function filterEventsByDate(events) {
    var filteredEvents = $.grep(events, filterDateFunction);
    return filteredEvents;
  }

  // The parameter selectRange is true if the range of dates was user selected.
  function updatePieChart(selectRange) {
    $('#chart_div').empty();
    tagTimes=new Array();	
    var pieChartTitle = computeTitle(selectRange);
    var filteredEvents = filterEventsByDate(unencryptedEvents);
    computeTagTimes(filteredEvents);
    drawChart(pieChartTitle);
  }

  function drawChart(pieChartTitle) {
    var data = new google.visualization.DataTable();
	  data.addColumn('string', 'Event');
    data.addColumn('number', 'Hours');
    for(var tag in tagTimes) {
      if (tag == '') {
        data.addRow(['Other',  tagTimes[tag]]);
      }
      else {
        data.addRow([tag,  tagTimes[tag]]);	 	
      }
    }
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, { chartArea:{width:"95%",height:"80%"}, width: 550, height: 360, title: "My Events for " + pieChartTitle + " (in hours)", titleTextStyle: {color: "Black", fontName: "Arial", fontSize: 20}});
  }
  $(document).ready(function(){
      var selectDate = function(dateText, inst) {
      var startDateText = $('#startPicker').val();
      var endDateText = $('#endPicker').val();

      if (startDateText != "" && endDateText != "") {
        startDate = Date.parse(startDateText);
        endDate = Date.parse(endDateText);
        $('#prevBtn' ).button( "option", "disabled", true );
        $('#nextBtn' ).button( "option", "disabled", true );
        updatePieChart(true);
      }
      }
      $('.datepicker').datepicker({onSelect: selectDate}); 

      $('#prevBtn').text('Previous ' + convertViewToDate[calendarView]);
      $('#nextBtn').text('Next ' + convertViewToDate[calendarView]);
      $('[type="button"]').button();

      $('#prevBtn').click(function(){
        if (calendarView == 'month') {
        startDate = startDate.add(-1).months();
        startDate.moveToFirstDayOfMonth();
        endDate = endDate.add(-1).months();
        endDate.moveToLastDayOfMonth();

        } else if (calendarView == 'agendaWeek') {
        startDate = startDate.add(-1).weeks();
        endDate = endDate.add(-1).weeks();
        } else {
        startDate = startDate.add(-1).days();
        endDate = endDate.add(-1).days();

        }
        updatePieChart();
        });
      $('#nextBtn').click(function(){
          if (calendarView == 'month') {
          startDate = startDate.add(1).months();
          startDate.moveToFirstDayOfMonth();
          endDate = endDate.add(1).months();
          endDate.moveToLastDayOfMonth();
          } else if (calendarView == 'agendaWeek') {
          startDate = startDate.add(1).weeks();
          endDate = endDate.add(1).weeks();
          } else {
          startDate = startDate.add(1).days();
          endDate = endDate.add(1).days();

          }
          updatePieChart();
          });

  });
</script>

app/views/events/edit.html.erb
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8"> </script>
<script type='text/javascript' src='/fullcalendar/fullcalendar.js'></script>

<ul id="toolbar" class="ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
  <p style="text-align:center"><big>Editing an Event</big></p>
</ul>
<br />

<%= render 'form' %>

<INPUT id="button" TYPE="button" NAME="myButton" VALUE="Update Event" >

<br />
<br />

app/views/events/new.html.erb
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8"> </script>
<script type='text/javascript' src='/fullcalendar/fullcalendar.js'></script>

<ul id="toolbar" class="ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
  <p style="text-align:center"><big>Creating a New Event</big></p>
</ul>
<br />
<%= render 'form' %>

<INPUT id="button" TYPE="button" NAME="myButton" VALUE="Create Event">

<br />
<br />

app/views/events/show.html.erb
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8"> </script>
<script type='text/javascript' src='/fullcalendar/fullcalendar.js'></script>

<ul id="toolbar" class="ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
  <p style="text-align:center"><big>Event Description</big></p>
</ul>
<br />
<%= render 'form' %>
<br />
<br />

<script type="text/javascript">
</script>
<script type="text/javascript" src="/csp_scripts/display_event.js"></script>

app/views/events/table.html.erb
<HEAD>
  <script type="text/javascript" charset="utf-8" src="/DataTables/jquery.js"></script>
  <script type="text/javascript" charset="utf-8" src="/DataTables/jquery.dataTables.js"></script>
</HEAD>
<!-- The table used is provided by the rails plugin rails_datatables.  This plugin
is a wrapper for the jquery library dataTables-->
<script type="text/javascript" src="/csp_scripts/table_init.js"></script>
<link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
<link type="text/css" rel="stylesheet" href="/jquery-ui-1.8.13/css/redmond/jquery-ui-1.8.13.custom.css"/>
<script src="/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript" charset="utf-8">
</script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<table id='events' class='datatable' width="100%" style= "text-align:center;">
  <thead>
    <tr>
      <th>Events Name</th>
      <th>Notes</th>
      <th>Category</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Map</th>
      <th/>
      <th/>
    </tr>
  </thead>
  <tbody>
    <% @events.each_with_index do |event,indexOfEvent| %>
      <tr class='event_row'>
        <td id='name'><%= link_to '', event, :class => 'eventData' %></td>
        <td id='notes'><%= link_to '', event, :class => 'eventData' %></td>
        <td id='tag'><%= link_to '', event, :class => 'eventData'  %></td>
        <td id='startTimeR'></td>
        <td id='endTimeR'></td>
        <td><%= link_to 'Map', "/#{@user.phone_number}/map/#{event.id}",
                :id => 'map_link', :class => 'mapping' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), :class => 'editing',
          :id => 'edit_link' %></td>
        <td><%= link_to 'Delete', event, :confirm => 'Are you sure?', :method => :delete,
                :phone_number => @user.phone_number %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<script type="text/javascript" src="/csp_scripts/table.js"></script>

app/views/events/user.html.erb
<% columns = [{:type => 'html', :class => "first"}, {:type => 'html'}, {:type => 'html'}, {:type => 'html'}, {:type => 'html'}, {:type => 'html'}, {:type => nil, :class => "last"},] %>
<%= raw datatable(columns, {:sort_by => "[2, 'desc']", :processing => image_tag("spinner.gif") }) %>
<h2>
  Showing all events for user with phone number '<%= @user.phone_number %>'
</h2>
<%= link_to 'Create a new Event', "/#{@user.phone_number}/new" %>

<table id='events' class='datatable'>
  <thead>
    <tr>
      <th>Events Name</th>
      <th>Notes</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @event_content_pairs.each do |event, content| %>
      <tr>
	<td><%= content['name'] %></td>
	<td><%= content['notes'] %></td>
	<td><%= content['startTime'] %></td>
	<td><%= content['endTime'] %></td>
	<td><%= link_to 'Map', "/#{@user.phone_number}/map/#{event.id}" %></td>
	<td><%= link_to 'Edit', edit_event_path(event) %></td>
	<td><%= link_to 'Delete', event, :confirm => 'Are you sure?', :method => :delete, :phone_number => @user.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>